# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('info', models.CharField(max_length=200)),
                ('defect', models.CharField(default='Нет дефектов', max_length=250)),
                ('type', models.CharField(choices=[('ЗАДВ', 'Задвижка'), ('ОК', 'Обратный клапан'), ('РЕГ', 'Регулятор'), ('Н', 'Насос'), ('ТА', 'Турбоагрегат'), ('Т/О', 'Теплообменник'), ('К', 'Конденсатор'), ('КС', 'Конденсатосборник'), ('Б', 'Бак'), ('ДРЕН', 'Дренаж')], default='ЗАДВ', max_length=4)),
                ('row', models.CharField(default='А-В', max_length=4)),
                ('axis', models.CharField(default='1-12', max_length=10)),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Чертеж/фото элемента')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=4)),
                ('info', models.CharField(max_length=250)),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Принципиальная схема')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Helper.System'),
        ),
    ]
