# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0003_auto_20170219_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Чертеж/фото элемента'),
        ),
        migrations.AlterField(
            model_name='system',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Принципиальная схема'),
        ),
        migrations.AlterField(
            model_name='system',
            name='info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
