# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0004_auto_20170219_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Элемент системы'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'Система'},
        ),
        migrations.AlterField(
            model_name='element',
            name='axis',
            field=models.CharField(default='1-12', max_length=10, verbose_name='Ось(оси)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='defect',
            field=models.CharField(default='Нет дефектов', max_length=250, verbose_name='Дефекты'),
        ),
        migrations.AlterField(
            model_name='element',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Чертеж,фото,схема'),
        ),
        migrations.AlterField(
            model_name='element',
            name='info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название и назначение'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Маркировка'),
        ),
        migrations.AlterField(
            model_name='element',
            name='row',
            field=models.CharField(default='А-В', max_length=4, verbose_name='Ряд(ы)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Helper.System', verbose_name='Система элемента'),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('ЗАДВ', 'Задвижка'), ('ОК', 'Обратный клапан'), ('РЕГ', 'Регулятор'), ('Н', 'Насос'), ('ТА', 'Турбоагрегат'), ('Т/О', 'Теплообменник'), ('К', 'Конденсатор'), ('КС', 'Конденсатосборник'), ('Б', 'Бак'), ('ДРЕН', 'Дренаж')], default='ЗАДВ', max_length=4, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='system',
            name='info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание системы'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='system',
            name='short_name',
            field=models.CharField(max_length=8, verbose_name='Короткое обозначение'),
        ),
    ]
