# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0005_auto_20170219_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name_plural': 'Элементы системы'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name_plural': 'Системы'},
        ),
    ]
